[project]
name = "bit-flip"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10,<3.13"
dependencies = [
    "numpy==1.26.4",
    "pandas==2.2.3",
    "pillow==11.2.1",
    "pyyaml==6.0.2",
    "torch==2.8.0",
    "torchvision==0.23.0",
    "tqdm==4.67.0",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

[tool.uv.sources]
torch = { index = "pytorch-cu128" }
torchvision = { index = "pytorch-cu128" }